# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dh5T5SDrt-4t51o7sJ6_n89MpmshQkpu
"""

a=[10,20,30,40]

type(a)

import numpy as np

x = np.array(a)

print(x)

type(x)

a=[1,2,3,4]
b=[10,20,30,40]
x=np.array([a,b])

print(x)

a=[1,2,3,4]
b=[10,20,30,40]
x = np.array([a,b])

print(x)

x = np.array([1,2,3,4], dtype = np.float32)
print(x)

x = np.zeros((2,3))
print(x)

x = np.zeros((4,4))
print(x)

np.ones((3,3))

np.ones(5, dtype = np.int32)

x = np.random.rand(2,5)

print(x)

np.random.rand??

np.random.randint(1,20, size = (3,3))

np.random.randint??

np.random.randn(2,5)

np.random.randn??

np.random.choice([2,3,4,7,8,10])

np.full((3,4),10)

np.ones((3,3))*10

x = np.eye(4, k = -1)
print(x)

np.eye??

np.arange(5,11)

np.arange(0,11,2)

np.linspace(0,1,5)

a=[10,20,30,40,50]
x= np.array(a)
print(x)

x.ndim

b=[1,2,3,4,5]
y=np.array([a,b])
print(y)

y.ndim

y.shape

y.size

a=np.array([3,6,9,12])
print(a)

np.reshape(a, (2,2))

a.reshape(2,2)

x = np.arange(1,16)
x

x.size

x.reshape(5,3)

x = np.arange(1,16)
print(x)

y = x.reshape(3,5)
print(y)

z = np.transpose(y)
print(z)

y.transpose()

a = np.arange(1,10)

print(a)

a[2:6]

x = np.arange(1,10).reshape(3,3)
print(x)

x[1,2]

x[1][2]

x[1:3,1:3]

a = np.arange(1,6)
b = np.arange(6,11)

print(a)

print(b)

x = np.vstack((a,b))

print(x)

x = np.hstack((a,b))

print(x)

a = np.arange(1,10).reshape(3,3)

b = np.arange(10,19).reshape(3,3)

print(a)

print(b)

np.concatenate((a,b))

np.concatenate((a,b), axis = 1)

a = np.arange(10,21,2)

b= np.array([[2],[2]])

print(a)

print(b)

z = a+b
print(z)

a = np.arange(10,21,2)

a+2

a-b

a*b

a = np.ones((3,3))
b = np.array([2])
print(a)

print(b)

a+b

a-b

a = np.eye(4)
print(a)

print(a+5)

a-1

a*2

a/0.5

np.sin(a)

np.cos(a)

np.sqrt(a)

a = np.arange(5,15,2)

print(a)

np.mean(a)

np.median(a)

np.std(a)

a = np.array([[1,6],[4,3]])
print(a)

print(np.min(a, axis = 0))

print(np.min(a, axis = 1))

print(np.max(a, axis = 1))

print(np.max(a, axis = 0))

a = np.array([1,4,3,10,20])

x = np.sort(a, kind = 'mergesort')

print(x)

A = np.arange(0,9).reshape(3,3)
B = np.ones((3,3))

print(A)

print(B)

np.dot(A,B)

A.dot(B)