# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/199noirAJS2TeeDpShu2qE6febjza8l8r
"""

import pandas as pd

import numpy as np

df=pd.read_csv("/content/student.csv")

df

df.head(10)

df.tail()

df.columns

df.columns.to_list()

df.info()

df.nunique()

df.head()

df['Club_Join_Data'] =df['Placement_Score'].apply(lambda x:x*(20/100))

df.head()

df['Reading_Score']=df['Writing_Score']-df['Math_Score']

df.head()

import matplotlib.pyplot as plt

plt.figure(figsize = (9,3))
plt.plot(df['Club_Join_Data'], df['Placement_Score'])
plt.show()