# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kwDQRO5YH_0xzsenI8vLNkw7nGo6QAF6
"""

x=5
print(type(x))
print(x)

x=5
y="john"
print(x)
print(y)

from os.path import isjunction
x=1
y=2.8
z=1j
print(type(x))
print(type(y))
print(type(z))

x=1
y=35656222554887711
z=-3255522
print(type(x))
print(type(y))
print(type(z))

x = 4
x="Sally"
x = 8
print(x)

x = str(3)
y=int(3)
z=float(3)
print(x)
print(y)
print(z)

x=1.10
y=1.0
z=-35.59
print(type(x))
print(type(y))
print(type(z))

x = 5
y = "John"
print(type(x))
print(type(y))

x=3+5j
y=5j
z=-5j
print(type(x))
print(type(y))
print(type(z))

x=1
y=2.8
z=1j
a=float(x)
b=int(y)
c=complex(x)
print(a)
print(b)
print(c)

x=int(1)
y=int(2.8)
z=int("3")
print(x)
print(y)
print(z)

x=float(1)
y=float(2.8)
z=float("3")
w=float("4.2")
print(x)
print(y)
print(z)
print(w)

a = 4
A="Sally"
print(a)
print(A)

x=str("s1")
y=str(2)
z=str(3.0)
print(x)
print(y)
print(z)

x,y,z="Orange", "banana","cherry"
print(x)
print(y)
print(z)

a="hello"
print(a)

a="""Lorem ipsum dolor sit amet,consectetur adipiscing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."""
print(a)

a="Hello, World!"
print(a[1])

for x in "banana":
  print(x)

a="Hello,World!"
print(len(a))

txt="The best things in life are free!"
print("free" in txt)

txt="The best things in life are free!"
if"free"in txt:
  print("Yes,'free'is present")

x,y,z="Orange", "banana","cherry"
print(x)
print(y)
print(z)

x=y=z="Orange"
print(x)
print(y)
print(z)

fruits=["apple","banana","cherry"]
x,y,z=fruits
print(x)
print(y)
print(z)

x="Python"
y="is"
z="awesome"
print(x,y,z)

x=1
y=35656222554887711
z=-3255522
print(type(x))
print(type(y))
print(type(z))

x=1.10
y=1.0
z=-35.59
print(type(x))
print(type(y))
print(type(z))

x=3+5j
y=5j
z=-5j
print(type(x))
print(type(y))
print(type(z))

txt="The best things in life are free!"
if"free"in txt:
  print("Yes,'free'is present")

txt="The best things in life are free!"
print("expensive" not in txt)

b="Hello, World!"
print(b[2:5])

a=b="Hello, World!"
print(b[:5])
print(b[2:])
print(b[-5:-2])
print(a.upper())
print(a.lower())

a=" Hello, World!"
print(len(a))
print(a.strip())
print(a.replace("H","J"))
print(a.split(","))

a="Hello"
b="World"
c=a + b
print(c)

print(10>9)
print(10==9)
print(10<9)

a=200
b=33
if b>a:
  print("b is greater than a")
else:
  print("b is not greater than a")

print(bool("Hello"))
print(bool(15))

mylist=["apple","banana","cherry"]
print(mylist)

thislist=["apple","banana","cherry"]
print(thislist)

thislist=["apple","banana","cherry","apple","cherry"]
print(thislist)

thislist=["apple","banana","cherry"]
print(len(thislist))

list1=["apple","banana","cherry"]
list2=[1,5,7,9,3]
list3=[True,False,False]
print(list1)
print(list2)
print(list3)

list1=["abc",34,True,40,"male"]
print(list1)

mylist=["apple","banana","cherry"]
print(mylist)

thislist=list(("apple","banana","cherry","orange","kiwi","melon","mango"))
print(thislist[1])
print(thislist[-1])
print(thislist[2:5])
print(thislist[:4])
print(thislist[-4:-1])

thislist=["apple","banana","cherry"]
thislist.append("orange")
print(thislist)
thislist.insert(1,"orange")
print(thislist)
thislist.remove("banana")
print(thislist)
for x in thislist:
  print(x)
  for i in range(len(thislist)):
    print(thislist[i])

mytuple=("apple","banana","cherry")
thistuple=("apple","banana","cherry")
print(thistuple)
print(thistuple[-1])
print(thistuple[1])

thistuple=("apple","banana","cherry","orange","kiwi","melon","mango")
print(thistuple[:4])

myset={"apple","banana","cherry"}
thisset={"apple","banana","cherry"}
print(thisset)

thisset={"apple","banana","cherry",True,1,2}
print(thisset)
thisset=("apple","banana","cherry")
print(thisset)

set1={"apple","banana","cherry"}
set2={1,5,7,9,3}
set3={True,False,False}
print(set1)
print(set2)
print(set3)

set1={"abc,34,True,40,male"}
print(set1)

thisset={"apple","banana","cherry"}
for x in thisset:
  print(x)

set1={"a","b","c"}
set2={1,2,3}
set3=set1.union(set2)
print(set3)

set1={"a","b","c"}
set2={1,2,3}
set3={"John","Elena"}
set4={"apple","banana","cherry"}
myset=set1.union(set2,set3,set4)
print(myset)

thisdict={
    "brand":"Ford",
    "model":"Mustang",
    "year":1964
}
print(thisdict)
print(thisdict["brand"])

thisdict={
    "brand":"Ford",
    "model":"Mustang",
    "year":1964,
    "year":2020
}
print(thisdict)
print(len(thisdict))

thisdict={
    "brand":"Ford",
    "electric":False,
    "year":1964,
    "colors":["red","white","blue"]
}
print(thisdict)

thisdict=dict(name="John",age=36,country="Norway")
print(thisdict)

a=33
b=200
if b>a:
  print("b is greater than a")

a=33
b=33
if b>a:
  print("b is greater than a")
elif a==b:
  print("a and b are equal")

a=200
b=33
if b>a:
  print("b is greater than a")
elif a==b:
  print("a and b are equal")
else:
  print("a is greater than b")

a=200
b=33
if b>a:
  print("b is greater than a")
else:
  print("b is not greater than a")

i=1
while i<6:
  print(i)
  i+=1

i=0
while i<6:
    i+=1
    if i==3:
      continue
    print(i)

i=1
while i<6:
  print(i)
  i+=1
else:
  print("i is no longer less than 6")

fruits=["apple","banana","cherry"]
for x in fruits:
  print(x)

fruits=["apple","banana","cherry"]
for x in fruits:
  print(x)
  if x=="banana":
    break

for x in range(6):
  print(x)

for x in range(2,30,3):
  print(x)

for x in range(2,6):
  print(x)

def my_function(fname):
  print(fname)
my_function("hello from a function")

def my_function(fname):
  print(fname+"Refsnes")
my_function("Emil")
my_function("Tobias")
my_function("Linus")

def my_function(fname,lname):
  print(fname+" "+lname)
my_function("Emil","Refsnes")

class MyClass:
  x=5
p1=MyClass()
print(p1.x)

class Person:
  def __init__(self,name,age):
    self.name=name
    self.age=age
p1=Person("John",36)
print(p1.name)
print(p1.age)

def myfunc():
  x=300
  def myinnerfunc():
    print(x)
  myinnerfunc()